### PR TITLE
fix(client): Export bug fixed

### PR DESCRIPTION
**Pull request by Ming424**
#

## Changes this PR introduces

- Bug fix for export button, rearrange the order of data
- Task linked:  [CU-q30yz9 Export CSV bug](https://app.clickup.com/t/q30yz9)

## How to test this PR

- Using export button from the inventory pages

## Notes for reviewers

- Try to export CSV

## Checklist

- [x] Have I renamed the title of this pull request to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)?
- [x] I will squash and merge when my PR is approved.
- [x] I have added tests to cover my changes (if applicable).

### CODE REVIEW

**Comment by Mackbellemore** [comment]
Task linked: [CU-q30yz9 Export CSV bug](https://app.clickup.com/t/q30yz9)

**Review by gordonpn — COMMENTED** [review]
Rename the PR title to follow conventional commits please.

**Comment by Ming424** [comment]
A filter will be applied for the future

**Review by DavidLiang01 — APPROVED** [review]

**Comment by gordonpn** [comment]
> A filter will be applied for the future

What do you mean filter? @Ming424

**Comment by Ming424** [comment]
> > A filter will be applied for the future
> 
> What do you mean filter? @Ming424 

Some raw data that is not shown frontend should be filtered out. For example defect id inside Part. I will add filter after every table is populated.

**Review by gordonpn — APPROVED** [review]

**Pull request merged**
