### PR TITLE
feat(client): better-looking login page 

### PR DESCRIPTION
**Pull request by KarinKazarian**
Co-authored-by: Sujan Saravanamuthu <tbksujan@users.noreply.github.com>

#

## Changes this PR introduces

-

## How to test this PR

-

## Notes for reviewers

-

## Checklist

- [x] I renamed the title of my pull request to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [x] I have added tests to cover my changes (if applicable).

### CODE REVIEW

**Comment by Mackbellemore** [comment]
Task linked: [CU-rn766x Add a little spice to login page](https://app.clickup.com/t/rn766x)

**Review by gordonpn — COMMENTED** [review]
The background image is too big and makes the page scrollable, is that expected?

I'm testing on 1920 x 1080 resolution

**Comment by SiuYe** [comment]
This login is fire 🔥 @tbksujan @KarinKazarian nice job!

**Review by SiuYe — DISMISSED** [review]

**Comment by SiuYe** [comment]
> The background image is too big and makes the page scrollable, is that expected?
> 
> I'm testing on 1920 x 1080 resolution

it does it on my side as well, but I don't find it too bad. But was it expected?

**Comment by sujvn** [comment]
@gordonpn @SiuYe image shouldn't scroll anymore

**Review by gordonpn — APPROVED** [review]
DMX passed away the same day this PR was opened 😢

**Review by DavidLiang01 — APPROVED** [review]

**Review by SiuYe — APPROVED** [review]
👍

**Pull request merged**
