### PR TITLE
feat(client): improve sidebar

### PR DESCRIPTION
**Pull request by sujvn**
#

## Changes this PR introduces

- New Sidebar

## How to test this PR

- Look at sidebar

## Notes for reviewers

-

## Checklist

- [x] I renamed the title of my pull request to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [x] I have added tests to cover my changes (if applicable).

### CODE REVIEW

**Comment by Mackbellemore** [comment]
Task linked: [CU-npzx1e Improve and style the sidebar](https://app.clickup.com/t/npzx1e)

**Review by DavidLiang01 — APPROVED** [review]
The sidebar looks amazing!

**Comment by DavidLiang01** [comment]
Is it better if you add an icon for the other pages that we didn't implement yet such as `scheduling `and `accounting`?

**Review by gordonpn — COMMENTED** [review]
So no text/labels for the icons, huh? 😑

**Comment by sujvn** [comment]
> Is it better if you add an icon for the other pages that we didn't implement yet such as `scheduling `and `accounting`?

I had the icons imported so that whoever did those pages could add it easily but the linting failed when I did that, so I'll just add it when those pages are done

**Comment by sujvn** [comment]
> So no text/labels for the icons, huh? 😑

I agree it's hard at first but my argument is that our users are going to be using this daily, it's not like they're only going to use it once and never use it again. After one day of use they'll most likely know what icon to click. but if other people agree with you i will change it

**Review by gordonpn — APPROVED** [review]

**Pull request merged**
