### PR TITLE
fix: use netlify toml to configure rewrites

### PR DESCRIPTION
**Pull request by gordonpn**
Refreshing the page on a path like `/login` doesn't return 404.

### CODE REVIEW

**Comment by Mackbellemore** [comment]
Task linked: [CU-mt0vfe Page refresh on paths returns 404](https://app.clickup.com/t/mt0vfe)

**Review by Mackbellemore — DISMISSED** [review]

**Review by SiuYe — APPROVED** [review]

**Review by nasjuice — APPROVED** [review]
🚀

**Comment by DavidLiang01** [comment]
Hey guys, how do you test this PR, do I use the link provided by zeet or run it on your local machine. I tried the zeet link, but it says it is forbidden.

**Comment by gordonpn** [comment]
> Hey guys, how do you test this PR, do I use the link provided by zeet or run it on your local machine. I tried the zeet link, but it says it is forbidden.
> 
> 

Hey David, try this link https://deploy-preview-28--soen-390-team-07.netlify.app/

**Review by DavidLiang01 — APPROVED** [review]

**Pull request merged**
