### PR TITLE
chore(server): Refactored MongoConnection and added user auth routes

### PR DESCRIPTION
**Pull request by Mackbellemore**
new endpoints: 
POST /user/login
body: {
  email: 
  password:
}

POST /user/register
body: {
  email: 
  password:
  username:
}

### CODE REVIEW

**Comment by Mackbellemore** [comment]
Task linked: [CU-krwq0w Server Endpoints for user login](https://app.clickup.com/t/krwq0w)

**Review by SiuYe — DISMISSED** [review]

**Comment by gordonpn** [comment]
> new endpoints:
> POST /user/login
> body: {
> email:
> password:
> }
> 
> POST /user/register
> body: {
> email:
> password:
> username:
> }

Should we look into Swagger/OpenAPI to document the endpoints?

Also, I'll take a look at the PR later today or tomorrow.

**Comment by Mackbellemore** [comment]
> > new endpoints:
> > POST /user/login
> > body: {
> > email:
> > password:
> > }
> > POST /user/register
> > body: {
> > email:
> > password:
> > username:
> > }
> 
> Should we look into Swagger/OpenAPI to document the endpoints?
> 
> Also, I'll take a look at the PR later today or tomorrow.

Hey Mr. Pham-Nguyen,
I will create a ticket for this,
all the best,
Mackbellemore

**Review by gordonpn — APPROVED** [review]
Looks great!

**Review by SiuYe — APPROVED** [review]

**Pull request merged**
