### PR TITLE
feat(client/server): Add logger and email notification in scheduling page

### PR DESCRIPTION
**Pull request by DavidLiang01**
#

## Changes this PR introduces

- Send email when machine is in maintenance in schedule page 
- Sen email when create new schedule
- Add logger to machine controller
- Limit scheduling page to Admin and manufacturing roles

## How to test this PR

- Test locally 

## ClickUp reference

CU-rkar9p 

## Notes for reviewers

-

## Checklist

- [x] I renamed the title of my pull request to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [x] I have added tests to cover my changes (if applicable).

### CODE REVIEW

**Comment by DavidLiang01** [comment]
Clickup task: [CU-rkar9p Add email notifications and logger in machine/scheduling page](https://app.clickup.com/t/rkar9p)

**Comment by Mackbellemore** [comment]
Task linked: [CU-rkar9p Add email notifications and logger in machine/scheduling page](https://app.clickup.com/t/rkar9p)

**Review by gordonpn — APPROVED** [review]
🍞🍞🍞

**Review by SiuYe — APPROVED** [review]
👍

**Pull request merged**
