### PR TITLE
fix(server): fix comparison operator for stock adjustment

### PR DESCRIPTION
**Pull request by Mackbellemore**
#

## Changes this PR introduces

- allows creating bikes with exactly the right amount of materials
- forgotten middlewares

## How to test this PR

- testing 123

## Notes for reviewers

- a note

## Checklist

- [x] I renamed the title of my pull request to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [x] I have added tests to cover my changes (if applicable).

### CODE REVIEW

**Comment by Mackbellemore** [comment]
Task linked: [CU-rk9qj3 Bike creation stock allocation bug](https://app.clickup.com/t/rk9qj3)

**Review by SiuYe — DISMISSED** [review]
➕➖✖➗ = 🖖

**Review by gordonpn — DISMISSED** [review]
👳🏽👳🏽👳🏽

**Review by gordonpn — APPROVED** [review]
🧨🧨🧨

**Review by SiuYe — APPROVED** [review]
‼

**Pull request merged**
