### PR TITLE
feat(client): search shipping location

### PR DESCRIPTION
**Pull request by DavidLiang01**
#

## Changes this PR introduces

- Able to find shipping location dynamically (Google-like search bar) when creating a new shipment on shipping, order, and sales pages

## How to test this PR

- Can be tested using Netlify link
- Try to input any value and see if any component breaks

## ClickUp reference

CU-qx7zwx

## Notes for reviewers

- Clickup [link](https://app.clickup.com/t/qx7zwx)

## Checklist

- [x] I renamed the title of my pull request to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [x] I have added tests to cover my changes (if applicable).

### CODE REVIEW

**Review by gordonpn — COMMENTED** [review]
I think you need to add the new location search bar to Orders and Sales page as well because I can still add a breaking location to the shipping page. (Check the shipping page on Netlify)

**Comment by Mackbellemore** [comment]
Task linked: [CU-qx7zwx Fix Mapbox Map](https://app.clickup.com/t/qx7zwx)

**Review by gordonpn — COMMENTED** [review]
Nothing appears as results for me when I type a location

**Review by gordonpn — DISMISSED** [review]
Cool shit

**Review by gordonpn — APPROVED** [review]

**Review by KarinKazarian — APPROVED** [review]
WOW, great job!!!

**Comment by DavidLiang01** [comment]
> Nothing appears as results for me when I type a location

**Pull request merged**
