### PR TITLE
chore: fix docker node_modules mount

### PR DESCRIPTION
**Pull request by gordonpn**
* Fix node_modules to be mounted in their respective named volume to avoid issues with the host filesystem
* `checkAdminRole` middleware was not skipping if `authEnabled` was set to false causing the GET `/users` endpoint to fail in development
* nyc code coverage now reports correctly controllers that aren't tested at all
* pre-commit hook will only format staged files (faster!)

### Important

If you need to install an npm package, you need to **attach a shell** to the container and install inside it.

**Friendly reminder**: You need to run `npm install` in the project root if you want the benefits of Husky hooks. (Only once, after you clone the repo)

### CODE REVIEW

**Comment by gordonpn** [comment]
Task linked: [CU-mpx5kg Fix Docker volumes](https://app.clickup.com/t/mpx5kg)

**Review by Mackbellemore — APPROVED** [review]

**Review by Mackbellemore — DISMISSED** [review]

**Review by nasjuice — APPROVED** [review]

**Review by SiuYe — APPROVED** [review]

**Review by nasjuice — APPROVED** [review]
didn't i approve this busting my balls 🔫

**Comment by gordonpn** [comment]
> didn't i approve this busting my balls 🔫

Stale reviews get dismissed loll

**Review by tbksujan — APPROVED** [review]
appreciate ur friendly reminder

**Review by DavidLiang01 — APPROVED** [review]

**Pull request merged**
